// 50+ Professional Resume Templates
export interface TemplateConfig {
    id: string;
    name: string;
    category: "professional" | "creative" | "minimal" | "executive" | "tech" | "academic";
    description: string;
    primaryColor: string;
    accentColor: string;
    fontFamily: string;
    layout: "single" | "double" | "sidebar-left" | "sidebar-right";
    headerStyle: "centered" | "left" | "split" | "banner";
    premium: boolean;
    preview: string; // Preview image path
}

export const TEMPLATE_CATEGORIES = [
    { id: "professional", name: "Professional", icon: "Briefcase" },
    { id: "creative", name: "Creative", icon: "Palette" },
    { id: "minimal", name: "Minimal", icon: "Minus" },
    { id: "executive", name: "Executive", icon: "Crown" },
    { id: "tech", name: "Tech & IT", icon: "Code" },
    { id: "academic", name: "Academic", icon: "GraduationCap" },
] as const;

export const RESUME_TEMPLATES: TemplateConfig[] = [
    // PROFESSIONAL TEMPLATES (1-10)
    {
        id: "classic-professional",
        name: "Classic Professional",
        category: "professional",
        description: "Timeless design trusted by Fortune 500 companies",
        primaryColor: "#1a1a2e",
        accentColor: "#4a90a4",
        fontFamily: "Georgia, serif",
        layout: "single",
        headerStyle: "centered",
        premium: false,
        preview: "/templates/classic-professional.png",
    },
    {
        id: "corporate-blue",
        name: "Corporate Blue",
        category: "professional",
        description: "Clean corporate style for business professionals",
        primaryColor: "#0f4c81",
        accentColor: "#2980b9",
        fontFamily: "'Inter', sans-serif",
        layout: "single",
        headerStyle: "left",
        premium: false,
        preview: "/templates/corporate-blue.png",
    },
    {
        id: "manhattan",
        name: "Manhattan",
        category: "professional",
        description: "Sophisticated New York corporate style",
        primaryColor: "#2c3e50",
        accentColor: "#e74c3c",
        fontFamily: "'Playfair Display', serif",
        layout: "single",
        headerStyle: "split",
        premium: false,
        preview: "/templates/manhattan.png",
    },
    {
        id: "london-executive",
        name: "London Executive",
        category: "professional",
        description: "British-inspired elegant professional design",
        primaryColor: "#1a1a1a",
        accentColor: "#c9a961",
        fontFamily: "'Cormorant Garamond', serif",
        layout: "single",
        headerStyle: "centered",
        premium: true,
        preview: "/templates/london-executive.png",
    },
    {
        id: "wall-street",
        name: "Wall Street",
        category: "professional",
        description: "Finance and banking industry standard",
        primaryColor: "#003366",
        accentColor: "#004d99",
        fontFamily: "'Times New Roman', serif",
        layout: "single",
        headerStyle: "left",
        premium: false,
        preview: "/templates/wall-street.png",
    },
    {
        id: "consulting-pro",
        name: "Consulting Pro",
        category: "professional",
        description: "McKinsey-style consulting resume",
        primaryColor: "#1e3a5f",
        accentColor: "#3498db",
        fontFamily: "'Calibri', sans-serif",
        layout: "single",
        headerStyle: "left",
        premium: true,
        preview: "/templates/consulting-pro.png",
    },
    {
        id: "silicon-valley",
        name: "Silicon Valley",
        category: "professional",
        description: "Tech startup professional style",
        primaryColor: "#2d3436",
        accentColor: "#6c5ce7",
        fontFamily: "'SF Pro Display', sans-serif",
        layout: "single",
        headerStyle: "centered",
        premium: false,
        preview: "/templates/silicon-valley.png",
    },
    {
        id: "amsterdam",
        name: "Amsterdam",
        category: "professional",
        description: "Modern European professional design",
        primaryColor: "#2c2c54",
        accentColor: "#ff6b6b",
        fontFamily: "'Montserrat', sans-serif",
        layout: "sidebar-left",
        headerStyle: "banner",
        premium: true,
        preview: "/templates/amsterdam.png",
    },
    {
        id: "tokyo-modern",
        name: "Tokyo Modern",
        category: "professional",
        description: "Clean Japanese-inspired minimalism",
        primaryColor: "#1a1a2e",
        accentColor: "#e94560",
        fontFamily: "'Noto Sans', sans-serif",
        layout: "single",
        headerStyle: "left",
        premium: false,
        preview: "/templates/tokyo-modern.png",
    },
    {
        id: "sydney-corporate",
        name: "Sydney Corporate",
        category: "professional",
        description: "Australian business professional style",
        primaryColor: "#0a3d62",
        accentColor: "#38ada9",
        fontFamily: "'Roboto', sans-serif",
        layout: "single",
        headerStyle: "centered",
        premium: false,
        preview: "/templates/sydney-corporate.png",
    },

    // CREATIVE TEMPLATES (11-20)
    {
        id: "creative-designer",
        name: "Creative Designer",
        category: "creative",
        description: "Bold design for creative professionals",
        primaryColor: "#6c5ce7",
        accentColor: "#fd79a8",
        fontFamily: "'Poppins', sans-serif",
        layout: "sidebar-left",
        headerStyle: "banner",
        premium: false,
        preview: "/templates/creative-designer.png",
    },
    {
        id: "portfolio-artist",
        name: "Portfolio Artist",
        category: "creative",
        description: "Showcase your creative work beautifully",
        primaryColor: "#2d3436",
        accentColor: "#00cec9",
        fontFamily: "'Raleway', sans-serif",
        layout: "double",
        headerStyle: "split",
        premium: true,
        preview: "/templates/portfolio-artist.png",
    },
    {
        id: "gradient-wave",
        name: "Gradient Wave",
        category: "creative",
        description: "Modern gradient design for innovators",
        primaryColor: "#667eea",
        accentColor: "#764ba2",
        fontFamily: "'DM Sans', sans-serif",
        layout: "single",
        headerStyle: "banner",
        premium: true,
        preview: "/templates/gradient-wave.png",
    },
    {
        id: "neon-glow",
        name: "Neon Glow",
        category: "creative",
        description: "Cyberpunk-inspired creative design",
        primaryColor: "#0f0f0f",
        accentColor: "#00ff88",
        fontFamily: "'Space Grotesk', sans-serif",
        layout: "sidebar-right",
        headerStyle: "left",
        premium: true,
        preview: "/templates/neon-glow.png",
    },
    {
        id: "pastel-dreams",
        name: "Pastel Dreams",
        category: "creative",
        description: "Soft, approachable creative style",
        primaryColor: "#dfe6e9",
        accentColor: "#e17055",
        fontFamily: "'Quicksand', sans-serif",
        layout: "single",
        headerStyle: "centered",
        premium: false,
        preview: "/templates/pastel-dreams.png",
    },
    {
        id: "geometric-bold",
        name: "Geometric Bold",
        category: "creative",
        description: "Strong geometric patterns and shapes",
        primaryColor: "#2c3e50",
        accentColor: "#f39c12",
        fontFamily: "'Bebas Neue', sans-serif",
        layout: "sidebar-left",
        headerStyle: "banner",
        premium: true,
        preview: "/templates/geometric-bold.png",
    },
    {
        id: "watercolor",
        name: "Watercolor",
        category: "creative",
        description: "Artistic watercolor-inspired design",
        primaryColor: "#34495e",
        accentColor: "#9b59b6",
        fontFamily: "'Crimson Text', serif",
        layout: "single",
        headerStyle: "centered",
        premium: true,
        preview: "/templates/watercolor.png",
    },
    {
        id: "retro-vintage",
        name: "Retro Vintage",
        category: "creative",
        description: "Classic vintage aesthetic",
        primaryColor: "#4a4a4a",
        accentColor: "#d4a574",
        fontFamily: "'Libre Baskerville', serif",
        layout: "single",
        headerStyle: "centered",
        premium: false,
        preview: "/templates/retro-vintage.png",
    },
    {
        id: "bauhaus",
        name: "Bauhaus",
        category: "creative",
        description: "Bauhaus movement inspired design",
        primaryColor: "#1a1a1a",
        accentColor: "#e63946",
        fontFamily: "'Futura', sans-serif",
        layout: "double",
        headerStyle: "split",
        premium: true,
        preview: "/templates/bauhaus.png",
    },
    {
        id: "swiss-design",
        name: "Swiss Design",
        category: "creative",
        description: "International typographic style",
        primaryColor: "#000000",
        accentColor: "#ff0000",
        fontFamily: "'Helvetica Neue', sans-serif",
        layout: "single",
        headerStyle: "left",
        premium: false,
        preview: "/templates/swiss-design.png",
    },

    // MINIMAL TEMPLATES (21-30)
    {
        id: "pure-minimal",
        name: "Pure Minimal",
        category: "minimal",
        description: "Ultra-clean minimalist design",
        primaryColor: "#000000",
        accentColor: "#333333",
        fontFamily: "'Inter', sans-serif",
        layout: "single",
        headerStyle: "left",
        premium: false,
        preview: "/templates/pure-minimal.png",
    },
    {
        id: "zen-simple",
        name: "Zen Simple",
        category: "minimal",
        description: "Inspired by Japanese simplicity",
        primaryColor: "#2d2d2d",
        accentColor: "#8b8b8b",
        fontFamily: "'Noto Serif', serif",
        layout: "single",
        headerStyle: "centered",
        premium: false,
        preview: "/templates/zen-simple.png",
    },
    {
        id: "nordic-clean",
        name: "Nordic Clean",
        category: "minimal",
        description: "Scandinavian minimalist aesthetic",
        primaryColor: "#333333",
        accentColor: "#5dade2",
        fontFamily: "'Source Sans Pro', sans-serif",
        layout: "single",
        headerStyle: "left",
        premium: false,
        preview: "/templates/nordic-clean.png",
    },
    {
        id: "whitespace",
        name: "Whitespace",
        category: "minimal",
        description: "Let your content breathe",
        primaryColor: "#1a1a1a",
        accentColor: "#666666",
        fontFamily: "'Lato', sans-serif",
        layout: "single",
        headerStyle: "centered",
        premium: false,
        preview: "/templates/whitespace.png",
    },
    {
        id: "mono-type",
        name: "Mono Type",
        category: "minimal",
        description: "Monospace typography focus",
        primaryColor: "#1e1e1e",
        accentColor: "#569cd6",
        fontFamily: "'JetBrains Mono', monospace",
        layout: "single",
        headerStyle: "left",
        premium: true,
        preview: "/templates/mono-type.png",
    },
    {
        id: "elegant-simple",
        name: "Elegant Simple",
        category: "minimal",
        description: "Simple yet sophisticated",
        primaryColor: "#2c2c2c",
        accentColor: "#9c8b7a",
        fontFamily: "'EB Garamond', serif",
        layout: "single",
        headerStyle: "centered",
        premium: false,
        preview: "/templates/elegant-simple.png",
    },
    {
        id: "grid-minimal",
        name: "Grid Minimal",
        category: "minimal",
        description: "Grid-based minimal layout",
        primaryColor: "#000000",
        accentColor: "#cccccc",
        fontFamily: "'Archivo', sans-serif",
        layout: "double",
        headerStyle: "split",
        premium: true,
        preview: "/templates/grid-minimal.png",
    },
    {
        id: "paper-minimal",
        name: "Paper Minimal",
        category: "minimal",
        description: "Clean paper document style",
        primaryColor: "#2c3e50",
        accentColor: "#7f8c8d",
        fontFamily: "'Crimson Pro', serif",
        layout: "single",
        headerStyle: "left",
        premium: false,
        preview: "/templates/paper-minimal.png",
    },
    {
        id: "line-minimal",
        name: "Line Minimal",
        category: "minimal",
        description: "Elegant line separators",
        primaryColor: "#1a1a1a",
        accentColor: "#4a4a4a",
        fontFamily: "'Spectral', serif",
        layout: "single",
        headerStyle: "centered",
        premium: false,
        preview: "/templates/line-minimal.png",
    },
    {
        id: "dot-minimal",
        name: "Dot Minimal",
        category: "minimal",
        description: "Subtle dot accents",
        primaryColor: "#333333",
        accentColor: "#e74c3c",
        fontFamily: "'Work Sans', sans-serif",
        layout: "single",
        headerStyle: "left",
        premium: false,
        preview: "/templates/dot-minimal.png",
    },

    // EXECUTIVE TEMPLATES (31-40)
    {
        id: "ceo-suite",
        name: "CEO Suite",
        category: "executive",
        description: "C-level executive resume design",
        primaryColor: "#1a1a2e",
        accentColor: "#c9a227",
        fontFamily: "'Playfair Display', serif",
        layout: "single",
        headerStyle: "centered",
        premium: true,
        preview: "/templates/ceo-suite.png",
    },
    {
        id: "board-room",
        name: "Board Room",
        category: "executive",
        description: "Designed for board-level positions",
        primaryColor: "#0c0c0c",
        accentColor: "#b8860b",
        fontFamily: "'Cormorant', serif",
        layout: "single",
        headerStyle: "left",
        premium: true,
        preview: "/templates/board-room.png",
    },
    {
        id: "private-equity",
        name: "Private Equity",
        category: "executive",
        description: "Investment executive style",
        primaryColor: "#1c2833",
        accentColor: "#1abc9c",
        fontFamily: "'Libre Baskerville', serif",
        layout: "single",
        headerStyle: "split",
        premium: true,
        preview: "/templates/private-equity.png",
    },
    {
        id: "fortune-500",
        name: "Fortune 500",
        category: "executive",
        description: "Enterprise executive format",
        primaryColor: "#0d1b2a",
        accentColor: "#3a86ff",
        fontFamily: "'Merriweather', serif",
        layout: "single",
        headerStyle: "centered",
        premium: true,
        preview: "/templates/fortune-500.png",
    },
    {
        id: "vp-level",
        name: "VP Level",
        category: "executive",
        description: "Vice President executive style",
        primaryColor: "#212529",
        accentColor: "#6c757d",
        fontFamily: "'Source Serif Pro', serif",
        layout: "single",
        headerStyle: "left",
        premium: true,
        preview: "/templates/vp-level.png",
    },
    {
        id: "managing-director",
        name: "Managing Director",
        category: "executive",
        description: "MD-level professional design",
        primaryColor: "#1e272e",
        accentColor: "#d63031",
        fontFamily: "'Lora', serif",
        layout: "single",
        headerStyle: "centered",
        premium: true,
        preview: "/templates/managing-director.png",
    },
    {
        id: "partner-track",
        name: "Partner Track",
        category: "executive",
        description: "Law & consulting partner style",
        primaryColor: "#2d3436",
        accentColor: "#0984e3",
        fontFamily: "'PT Serif', serif",
        layout: "single",
        headerStyle: "left",
        premium: true,
        preview: "/templates/partner-track.png",
    },
    {
        id: "senior-leadership",
        name: "Senior Leadership",
        category: "executive",
        description: "Senior management design",
        primaryColor: "#1a1a1a",
        accentColor: "#2ecc71",
        fontFamily: "'Domine', serif",
        layout: "single",
        headerStyle: "split",
        premium: false,
        preview: "/templates/senior-leadership.png",
    },
    {
        id: "global-executive",
        name: "Global Executive",
        category: "executive",
        description: "International executive style",
        primaryColor: "#0a192f",
        accentColor: "#64ffda",
        fontFamily: "'Cardo', serif",
        layout: "single",
        headerStyle: "centered",
        premium: true,
        preview: "/templates/global-executive.png",
    },
    {
        id: "prestige",
        name: "Prestige",
        category: "executive",
        description: "Ultimate executive prestige",
        primaryColor: "#000000",
        accentColor: "#a67c00",
        fontFamily: "'Cinzel', serif",
        layout: "single",
        headerStyle: "centered",
        premium: true,
        preview: "/templates/prestige.png",
    },

    // TECH TEMPLATES (41-48)
    {
        id: "developer-dark",
        name: "Developer Dark",
        category: "tech",
        description: "Dark mode for developers",
        primaryColor: "#0d1117",
        accentColor: "#58a6ff",
        fontFamily: "'Fira Code', monospace",
        layout: "sidebar-left",
        headerStyle: "left",
        premium: false,
        preview: "/templates/developer-dark.png",
    },
    {
        id: "github-style",
        name: "GitHub Style",
        category: "tech",
        description: "Inspired by GitHub's design",
        primaryColor: "#24292e",
        accentColor: "#2ea44f",
        fontFamily: "'Inter', sans-serif",
        layout: "single",
        headerStyle: "split",
        premium: false,
        preview: "/templates/github-style.png",
    },
    {
        id: "stack-overflow",
        name: "Stack Overflow",
        category: "tech",
        description: "Developer community style",
        primaryColor: "#232629",
        accentColor: "#f48024",
        fontFamily: "'Source Sans Pro', sans-serif",
        layout: "single",
        headerStyle: "left",
        premium: false,
        preview: "/templates/stack-overflow.png",
    },
    {
        id: "terminal",
        name: "Terminal",
        category: "tech",
        description: "Command line interface style",
        primaryColor: "#1e1e1e",
        accentColor: "#4ec9b0",
        fontFamily: "'Cascadia Code', monospace",
        layout: "single",
        headerStyle: "left",
        premium: true,
        preview: "/templates/terminal.png",
    },
    {
        id: "devops-engineer",
        name: "DevOps Engineer",
        category: "tech",
        description: "Infrastructure and DevOps focus",
        primaryColor: "#172b4d",
        accentColor: "#0052cc",
        fontFamily: "'IBM Plex Sans', sans-serif",
        layout: "sidebar-left",
        headerStyle: "banner",
        premium: false,
        preview: "/templates/devops-engineer.png",
    },
    {
        id: "data-scientist",
        name: "Data Scientist",
        category: "tech",
        description: "Data science and ML focus",
        primaryColor: "#1a1a2e",
        accentColor: "#e94560",
        fontFamily: "'Roboto Mono', monospace",
        layout: "single",
        headerStyle: "centered",
        premium: true,
        preview: "/templates/data-scientist.png",
    },
    {
        id: "cloud-architect",
        name: "Cloud Architect",
        category: "tech",
        description: "Cloud and infrastructure design",
        primaryColor: "#232f3e",
        accentColor: "#ff9900",
        fontFamily: "'Amazon Ember', sans-serif",
        layout: "sidebar-right",
        headerStyle: "split",
        premium: true,
        preview: "/templates/cloud-architect.png",
    },
    {
        id: "fullstack-modern",
        name: "Full Stack Modern",
        category: "tech",
        description: "Modern full-stack developer",
        primaryColor: "#1e1e2e",
        accentColor: "#89b4fa",
        fontFamily: "'JetBrains Mono', monospace",
        layout: "single",
        headerStyle: "left",
        premium: false,
        preview: "/templates/fullstack-modern.png",
    },

    // ACADEMIC TEMPLATES (49-55)
    {
        id: "harvard-academic",
        name: "Harvard Academic",
        category: "academic",
        description: "Ivy League academic CV style",
        primaryColor: "#a51c30",
        accentColor: "#1e1e1e",
        fontFamily: "'EB Garamond', serif",
        layout: "single",
        headerStyle: "centered",
        premium: false,
        preview: "/templates/harvard-academic.png",
    },
    {
        id: "research-scholar",
        name: "Research Scholar",
        category: "academic",
        description: "Academic research focus",
        primaryColor: "#2c3e50",
        accentColor: "#27ae60",
        fontFamily: "'Linux Libertine', serif",
        layout: "single",
        headerStyle: "left",
        premium: false,
        preview: "/templates/research-scholar.png",
    },
    {
        id: "phd-candidate",
        name: "PhD Candidate",
        category: "academic",
        description: "Doctoral student CV",
        primaryColor: "#1a1a1a",
        accentColor: "#3498db",
        fontFamily: "'Computer Modern', serif",
        layout: "single",
        headerStyle: "centered",
        premium: false,
        preview: "/templates/phd-candidate.png",
    },
    {
        id: "professor-cv",
        name: "Professor CV",
        category: "academic",
        description: "University professor style",
        primaryColor: "#003262",
        accentColor: "#fdb515",
        fontFamily: "'Palatino', serif",
        layout: "single",
        headerStyle: "left",
        premium: true,
        preview: "/templates/professor-cv.png",
    },
    {
        id: "medical-resident",
        name: "Medical Resident",
        category: "academic",
        description: "Medical and healthcare CV",
        primaryColor: "#0077b6",
        accentColor: "#00b4d8",
        fontFamily: "'Georgia', serif",
        layout: "single",
        headerStyle: "centered",
        premium: false,
        preview: "/templates/medical-resident.png",
    },
    {
        id: "law-review",
        name: "Law Review",
        category: "academic",
        description: "Legal academic style",
        primaryColor: "#1a1a1a",
        accentColor: "#8b0000",
        fontFamily: "'Times New Roman', serif",
        layout: "single",
        headerStyle: "left",
        premium: true,
        preview: "/templates/law-review.png",
    },
    {
        id: "postdoc-fellow",
        name: "Postdoc Fellow",
        category: "academic",
        description: "Postdoctoral researcher CV",
        primaryColor: "#2d3142",
        accentColor: "#ef8354",
        fontFamily: "'Garamond', serif",
        layout: "single",
        headerStyle: "centered",
        premium: false,
        preview: "/templates/postdoc-fellow.png",
    },
];

// Type aliases for compatibility
export type ResumeTemplate = TemplateConfig & { colors: { primary: string; secondary: string; background: string }; };
export type TemplateCategory = TemplateConfig["category"];

// Helper to transform template with colors
const addColors = (t: TemplateConfig): ResumeTemplate => ({
    ...t,
    colors: {
        primary: t.primaryColor,
        secondary: t.accentColor,
        background: "#f8fafc",
    }
});

// Alias for easier import
export const templates: ResumeTemplate[] = RESUME_TEMPLATES.map(addColors);

export const getTemplatesByCategory = (category: string): ResumeTemplate[] => {
    return RESUME_TEMPLATES.filter((t) => t.category === category).map(addColors);
};

export const getTemplateById = (id: string): ResumeTemplate | undefined => {
    const template = RESUME_TEMPLATES.find((t) => t.id === id);
    return template ? addColors(template) : undefined;
};

export const getFreeTemplates = (): ResumeTemplate[] => {
    return RESUME_TEMPLATES.filter((t) => !t.premium).map(addColors);
};

export const getPremiumTemplates = (): ResumeTemplate[] => {
    return RESUME_TEMPLATES.filter((t) => t.premium).map(addColors);
};
