"use client";

import { useFormContext } from "react-hook-form";
import type { ResumeFormData } from "@/lib/validators/resumeSchema";
import { User, Briefcase, GraduationCap, Target } from "lucide-react";

export default function ReviewStep() {
    const { getValues } = useFormContext<ResumeFormData>();
    const data = getValues();

    return (
        <div className="animate-fade-in space-y-8">
            <div>
                <h2 className="text-xl font-semibold mb-1" style={{ color: "var(--color-text)" }}>
                    Review Your Details
                </h2>
                <p className="text-sm" style={{ color: "var(--color-text-muted)" }}>
                    Make sure everything looks right before we generate your resume.
                </p>
            </div>

            {/* Personal Info Summary */}
            <section className="p-5" style={{ border: "1px solid rgba(201,169,110,0.08)", background: "rgba(201,169,110,0.02)", borderRadius: "2px" }}>
                <h3 className="font-semibold flex items-center gap-2 mb-4" style={{ color: "var(--color-primary)" }}>
                    <User size={18} />
                    Personal Information
                </h3>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-y-4 gap-x-6 text-sm">
                    <div>
                        <span className="block opacity-60 text-xs uppercase tracking-wider mb-1">Name</span>
                        <span className="font-medium">{data.fullName || "—"}</span>
                    </div>
                    <div>
                        <span className="block opacity-60 text-xs uppercase tracking-wider mb-1">Email</span>
                        <span>{data.email || "—"}</span>
                    </div>
                    <div>
                        <span className="block opacity-60 text-xs uppercase tracking-wider mb-1">Phone</span>
                        <span>{data.phone || "—"}</span>
                    </div>
                    <div className="col-span-2 sm:col-span-3">
                        <span className="block opacity-60 text-xs uppercase tracking-wider mb-1">Summary</span>
                        <p className="leading-relaxed">{data.summary || "Will be generated by AI"}</p>
                    </div>
                </div>
            </section>

            {/* Experience Summary */}
            <section className="p-5" style={{ border: "1px solid rgba(201,169,110,0.08)", background: "rgba(201,169,110,0.02)", borderRadius: "2px" }}>
                <h3 className="font-semibold flex items-center gap-2 mb-4" style={{ color: "var(--color-primary)" }}>
                    <Briefcase size={18} />
                    Work Experience
                </h3>
                <div className="space-y-4">
                    {data.experiences.map((exp, i) => (
                        <div key={i} className="text-sm">
                            <div className="font-medium">{exp.jobTitle} at {exp.company}</div>
                            <div className="opacity-60 text-xs mb-1">
                                {exp.startDate} – {exp.isCurrent ? "Present" : exp.endDate}
                            </div>
                            <p className="opacity-80 line-clamp-2">{exp.description}</p>
                        </div>
                    ))}
                </div>
            </section>

            {/* Education Summary */}
            <section className="p-5" style={{ border: "1px solid rgba(201,169,110,0.08)", background: "rgba(201,169,110,0.02)", borderRadius: "2px" }}>
                <h3 className="font-semibold flex items-center gap-2 mb-4" style={{ color: "var(--color-primary)" }}>
                    <GraduationCap size={18} />
                    Education
                </h3>
                <div className="space-y-4">
                    {data.education.map((edu, i) => (
                        <div key={i} className="text-sm">
                            <div className="font-medium">{edu.degree} in {edu.fieldOfStudy}</div>
                            <div className="opacity-60 text-xs">
                                {edu.institution}, {edu.graduationYear} {edu.gpa ? `(GPA: ${edu.gpa})` : ""}
                            </div>
                        </div>
                    ))}
                </div>
            </section>

            {/* Skills Summary */}
            <section className="p-5" style={{ border: "1px solid rgba(201,169,110,0.08)", background: "rgba(201,169,110,0.02)", borderRadius: "2px" }}>
                <h3 className="font-semibold flex items-center gap-2 mb-4" style={{ color: "var(--color-primary)" }}>
                    <Target size={18} />
                    Skills &amp; Target Role
                </h3>
                <div className="space-y-4 text-sm">
                    <div>
                        <span className="block opacity-60 text-xs uppercase tracking-wider mb-1">Target Role</span>
                        <span className="font-medium text-lg">{data.targetJobTitle || "—"}</span>
                    </div>
                    <div>
                        <span className="block opacity-60 text-xs uppercase tracking-wider mb-1">Tech Skills</span>
                        <div className="flex flex-wrap gap-1 mt-1">
                            {data.technicalSkills.map((s) => (
                                <span key={s} className="px-2 py-0.5 text-xs" style={{ background: "rgba(201,169,110,0.1)", color: "var(--color-primary)", borderRadius: "2px" }}>{s}</span>
                            ))}
                        </div>
                    </div>
                </div>
            </section>
        </div>
    );
}
